apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server-deployment
  labels:
    app: echo-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
      annotations:
        # WARNING: This simulates the service account being exposed via an annotation.
        cloud.google.com/service_account: "name@prod-project-id.iam.gserviceaccount.com"
    spec:
      containers:
      - name: echo-server
        #image: docker.io/alexeytarasovpa/oss-na24-slsa-workshop-project1-echo-server@sha256:4004ae316501b67d4d2f7eb82b02f36f32f91101cc9a53d5eb4dd044c16a552e
        image: docker.io/atarasov8888/oss-na24-slsa-workshop-project1-echo-server@sha256:89b928c25bfc1d7069de4e9e29508f234ffb8f5c8b819058b7f380a7692f5929
        ports:
        - containerPort: 8081
